name: aplikasi_berita
description: "Aplikasi berita terintegrasi dengan backend Node.js"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  
  # Google Login
  google_sign_in: ^6.1.6

  # State Management & Local Storage
  provider: ^6.0.5
  shared_preferences: ^2.2.2

  # Upload Gambar
  image_picker: ^1.1.2

  # Firebase Integration
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.9
  firebase_storage: ^11.7.0 
  cloud_firestore: ^4.17.0 # <-- TAMBAHKAN INI

  # Add crypto package
  crypto: ^3.0.0
  emoji_picker_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
