name: aplikasi_berita
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.2.5

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6

  # UI & Utility
  cupertino_icons: ^1.0.8
  timeago: ^3.7.1
  html: ^0.15.4
  webview_flutter: ^4.4.4

  # Share & HTML Rendering
  share_plus: ^9.0.0
  flutter_html: ^3.0.0-beta.2 # <-- DITAMBAHKAN DI SINI

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true