// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpjmeYzrDGBGxL-n6LaomhUohuMELzso',
    appId: '1:764848971069:web:968b9128e4c4164b043954',
    messagingSenderId: '764848971069',
    projectId: 'berita-komentar-maftuh',
    authDomain: 'berita-komentar-maftuh.firebaseapp.com',
    storageBucket: 'berita-komentar-maftuh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzk3YHETn5JGaASLx95TECXPiZh5xXXuE',
    appId: '1:764848971069:android:8946b0f3ff85d4de043954',
    messagingSenderId: '764848971069',
    projectId: 'berita-komentar-maftuh',
    storageBucket: 'berita-komentar-maftuh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGQP6A27rZsXQ9UwlanebejsNepQK0Z4E',
    appId: '1:764848971069:ios:9caa8d812ff5f1f4043954',
    messagingSenderId: '764848971069',
    projectId: 'berita-komentar-maftuh',
    storageBucket: 'berita-komentar-maftuh.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBerita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGQP6A27rZsXQ9UwlanebejsNepQK0Z4E',
    appId: '1:764848971069:ios:9caa8d812ff5f1f4043954',
    messagingSenderId: '764848971069',
    projectId: 'berita-komentar-maftuh',
    storageBucket: 'berita-komentar-maftuh.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiBerita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxpjmeYzrDGBGxL-n6LaomhUohuMELzso',
    appId: '1:764848971069:web:f3ca27d16e834b7d043954',
    messagingSenderId: '764848971069',
    projectId: 'berita-komentar-maftuh',
    authDomain: 'berita-komentar-maftuh.firebaseapp.com',
    storageBucket: 'berita-komentar-maftuh.firebasestorage.app',
  );
}
